apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.0.11
    helm.sh/chart: argo-cd-8.1.3
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
data:
  # Default policy for authenticated users - gives read/write access to applications and repositories
  policy.default: role:developer
  
  # CSV policies defining roles
  policy.csv: |
    # Developer role - can view and manage applications
    p, role:developer, applications, *, */*, allow
    p, role:developer, repositories, *, *, allow
    p, role:developer, certificates, *, *, allow
    p, role:developer, clusters, get, *, allow
    p, role:developer, projects, get, *, allow
    
    # Admin role (for reference)
    p, role:admin, *, *, *, allow
    
    # Grant admin role to the built-in admin user
    g, admin, role:admin
  
  policy.matchMode: glob
  scopes: '[groups]' 