apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "k8s-tracker-database.fullname" . }}-nfs-pv
  labels:
    {{- include "k8s-tracker-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}/{{ include "k8s-tracker-database.fullname" . }} 