apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-tracker-database.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ include "k8s-tracker-database.fullname" . }}-nfs-pv 