apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "k8s-tracker-database.selectorLabels" . | nindent 4 }} 