{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-tracker-controller.fullname" . }}
  labels:
    {{- include "k8s-tracker-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-tracker-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-tracker-controller.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }} 