{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-tracker-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
{{- end }} 