apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tracker-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kingoftowns/k8s-tracker.git
    targetRevision: HEAD
    path: argocd/base/backend
    helm:
      valueFiles:
        - ../../environments/pi4/backend-values.yaml  # TODO: Update for your environment
  destination:
    name: pi4  # External pi4 cluster (registered in ArgoCD)
    namespace: cluster-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # Wait for database to be ready
  info:
    - name: 'Depends on'
      value: 'k8s-tracker-database' 