apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tracker-controller-pi4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kingoftowns/k8s-tracker.git
    targetRevision: HEAD
    path: argocd/base/controller
    helm:
      valueFiles:
        - ../../environments/pi4/controller-values.yaml
  destination:
    server: https://10.0.8.11:6443  # External pi4 cluster
    namespace: cluster-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 