apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tracker-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kingoftowns/k8s-tracker.git
    targetRevision: HEAD
    path: argocd/base/controller
    helm:
      valueFiles:
        - ../../environments/pi5/controller-values.yaml  # TODO: Update for your environment
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # Wait for backend to be ready
  info:
    - name: 'Depends on'
      value: 'k8s-tracker-backend' 