apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tracker-controller-pi5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kingoftowns/k8s-tracker.git
    targetRevision: HEAD
    path: argocd/base/controller
    helm:
      valueFiles:
        - ../../environments/pi5/controller-values.yaml
  destination:
    server: https://kubernetes.default.svc  # pi5 cluster (where ArgoCD is running)
    namespace: cluster-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 