apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tracker-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kingoftowns/k8s-tracker.git
    targetRevision: HEAD
    path: argocd/base/database
    helm:
      valueFiles:
        - ../../environments/pi4/database-values.yaml  # TODO: Update for your environment
  destination:
    server: https://10.0.8.11:6443  # External pi4 cluster
    namespace: cluster-tracker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data 