apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-tracker-frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-frontend.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-tracker-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-tracker-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: REACT_APP_CLUSTER_API_URL
              value: {{ .Values.apiUrl | quote }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }} 