{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  commonName: {{ .Values.certificate.commonName }}
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
    group: {{ .Values.certificate.issuerRef.group }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
{{- end }} 