apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-tracker-backend.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-tracker-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-tracker-backend.selectorLabels" . | nindent 4 }} 