apiVersion: v2
name: k8s-tracker-frontend
description: Frontend Dashboard for Kubernetes Tracker (React)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - frontend
  - react
  - dashboard
  - kubernetes-tracker
home: https://github.com/kingoftowns/k8s-tracker
sources:
  - https://github.com/kingoftowns/k8s-tracker
maintainers:
  - name: Your Name
    email: your-email@example.com
dependencies: [] 